services:
  postgres:
    image: 'postgres:16'
    container_name: recipes-demo-postgres
    restart: always
    environment:
      POSTGRES_DB: recipes_demo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipes-demo-net

volumes:
  postgres_data:

networks:
  recipes-demo-net:
    driver: bridge
    name: recipes-demo-net